### PR TITLE
Alpha updates

### PR DESCRIPTION
**Pull request by matt-oneill**
Based on the updates to Alpha API this morning, I believe these are the changes required to this library.
Updated postman collection, all endpoints are working in postman, and updated the library to reflect this.
** I HAVE NOT BEEN ABLE TO TEST THE LIBRARY **

### CODE REVIEW

**Review by CharlesGillanders — APPROVED** [review]
Thank you!

**Comment by SorX14** [comment]
Beat me by a few minutes, nice work

**Comment by CharlesGillanders** [comment]
There was a tiny typo in the variable name todayDate - I've fixed that and confirmed the library works.  I'll update PyPi and my home assistant component.

**Comment by matt-oneill** [comment]
Thanks Charles apologies for the typo it was done in a browser at 7am as I didn’t have access to my dev machine to test it

**Pull request merged**
